export const defaultProcSettings = [
    {
      name: "Default Proctoring",
      settings: {
        recordWebcam: true,
        recordScreen: true,
        recordAudio: false,
        chat: false,
        studentPicture: true,
        studentIdDl: true,
        roomScan: false,
        otp: false,
        calculatorAllowed: true,
        scratchPadAllowed: true,
        liveHelp: false,
        whitelistPages: false,
        disableCopyPaste: true,
        disablePrinting: true,
        multiplePerson: true,
        cellPhone: true,
        noPersonInRoom: true,
        speaking: true,
        postExamReview: true,
        examdLiveLaunch: false,
        instructorProctored: false,
        examdProctored: false,
        lockdownBrowser: false,
      },
    },
    {
      name: "Default w/ Live launch",
      settings: {
        recordWebcam: false,
        recordScreen: true,
        recordAudio: false,
        chat: false,
        studentPicture: false,
        studentIdDl: false,
        roomScan: true,
        otp: false,
        calculatorAllowed: false,
        scratchPadAllowed: false,
        liveHelp: false,
        whitelistPages: false,
        disableCopyPaste: true,
        disablePrinting: true,
        multiplePerson: true,
        cellPhone: true,
        noPersonInRoom: true,
        speaking: true,
        postExamReview: true,
        examdLiveLaunch: true,
        instructorProctored: false,
        examdProctored: false,
        lockdownBrowser: false,
      },
    },
    {
      name: "Default w/ Live Proctoring",
      settings: {
        recordWebcam: false,
        recordScreen: true,
        recordAudio: false,
        chat: false,
        studentPicture: true,
        studentIdDl: true,
        roomScan: false,
        otp: false,
        calculatorAllowed: false,
        scratchPadAllowed: false,
        liveHelp: false,
        whitelistPages: false,
        disableCopyPaste: true,
        disablePrinting: true,
        multiplePerson: true,
        cellPhone: true,
        noPersonInRoom: true,
        speaking: true,
        postExamReview: true,
        examdLiveLaunch: false,
        instructorProctored: true,
        examdProctored: false,
        lockdownBrowser: false,
      },
    },
    {
      name: "Lock down Browser",
      settings: {
        recordWebcam: false,
        recordScreen: false,
        recordAudio: false,
        chat: false,
        studentPicture: true,
        studentIdDl: true,
        roomScan: false,
        otp: false,
        calculatorAllowed: false,
        scratchPadAllowed: false,
        liveHelp: false,
        whitelistPages: false,
        disableCopyPaste: true,
        disablePrinting: true,
        multiplePerson: false,
        cellPhone: false,
        noPersonInRoom: false,
        speaking: false,
        postExamReview: false,
        examdLiveLaunch: false,
        instructorProctored: false,
        examdProctored: false,
        lockdownBrowser: true,
      },
    }
  ];