import { defualtProctingSettings } from "../AppTypes";

export const defaultProcSettings: defualtProctingSettings[] = [
  {
    name: "AI Proctoring",
    infoMsg:
      "AI-based proctoring is a process that assesses a test-taking individual’s behavior, environment and movement, similar to a human proctor. In AI-based proctoring, the AI algorithm is trained by experts to predict, flag and register even the minutest of discrepancies and suspicion.",
    settings: {
      recordWebcam: true,
      recordScreen: true,
      recordAudio: false,
      chat: false,
      studentPicture: true,
      studentIdDl: true,
      roomScan: false,
      otp: false,
      calculatorAllowed: true,
      scratchPadAllowed: true,
      liveHelp: false,
      whitelistPages: false,
      disableCopyPaste: true,
      disablePrinting: true,
      multiplePerson: true,
      cellPhone: true,
      noPersonInRoom: true,
      speaking: true,
      postExamReview: true,
      examdLiveLaunch: false,
      instructorProctored: false,
      examdProctored: false,
      lockdownBrowser: false,
    },
  },
  {
    name: "Live Launch",
    infoMsg:
      "Live Proctoring is an identity verification at the beginning of the exam or quiz. Here a human from our side will let the student start the quiz after verifying his/her identity.",
    settings: {
      recordWebcam: true,
      recordScreen: true,
      recordAudio: false,
      chat: false,
      studentPicture: false,
      studentIdDl: false,
      roomScan: true,
      otp: false,
      calculatorAllowed: false,
      scratchPadAllowed: false,
      liveHelp: false,
      whitelistPages: false,
      disableCopyPaste: true,
      disablePrinting: true,
      multiplePerson: true,
      cellPhone: true,
      noPersonInRoom: true,
      speaking: true,
      postExamReview: true,
      examdLiveLaunch: true,
      instructorProctored: false,
      examdProctored: false,
      lockdownBrowser: false,
    },
  },
  {
    name: "Live Proctoring",
    infoMsg:
      "Live Proctoring is an identity verification and automated digital remote proctoring solution, helping Institutions of higher education ensure the integrity of their high-stakes online assessments. Here a human either from Institution or from our side will monitor the full exam.",
    settings: {
      recordWebcam: true,
      recordScreen: true,
      recordAudio: false,
      chat: false,
      studentPicture: true,
      studentIdDl: true,
      roomScan: false,
      otp: false,
      calculatorAllowed: false,
      scratchPadAllowed: false,
      liveHelp: false,
      whitelistPages: false,
      disableCopyPaste: true,
      disablePrinting: true,
      multiplePerson: true,
      cellPhone: true,
      noPersonInRoom: true,
      speaking: true,
      postExamReview: true,
      examdLiveLaunch: false,
      instructorProctored: true,
      examdProctored: false,
      lockdownBrowser: false,
    },
  },
  {
    name: "Lockdown Browser",
    infoMsg:
      "Lockdown browser is an advanced technology that locks down test-takers' testing environment and restricts on-screen cheating during an online exam. It does not do video recording like the other options.",
    settings: {
      recordWebcam: false,
      recordScreen: false,
      recordAudio: false,
      chat: false,
      studentPicture: true,
      studentIdDl: true,
      roomScan: false,
      otp: false,
      calculatorAllowed: false,
      scratchPadAllowed: false,
      liveHelp: false,
      whitelistPages: false,
      disableCopyPaste: true,
      disablePrinting: true,
      multiplePerson: false,
      cellPhone: false,
      noPersonInRoom: false,
      speaking: false,
      postExamReview: false,
      examdLiveLaunch: false,
      instructorProctored: false,
      examdProctored: false,
      lockdownBrowser: true,
    },
  },
];
