import { defualtProctingSettings, GeneralInstructions, QuizConfigurationWithOnlyProcOpt } from "../AppTypes";

export const defaultProcSettings: defualtProctingSettings[] = [
  {
    name: "Report Review",
    configName: "reportReview",
    infoMsg:
      "Please click this check box, if you want Examd to review the report. If checked, Examd will check all the violation reports for the selected quiz and provide a Pass/Fail remark. Instructor can then revisit any of the report if they wish to do so.",
    settings: {
      recordWebcam: true,
      recordScreen: true,
      recordAudio: false,
      chat: false,
      studentPicture: true,
      studentIdDl: true,
      roomScan: false,
      otp: false,
      calculatorAllowed: true,
      scratchPadAllowed: true,
      liveHelp: false,
      whitelistPages: false,
      disableCopyPaste: true,
      disablePrinting: true,
      multiplePerson: true,
      cellPhone: true,
      noPersonInRoom: true,
      speaking: true,
      postExamReview: true,
      examdLiveLaunch: false,
      instructorProctored: false,
      examdProctored: false,
      lockdownBrowser: false,
    },
  },
  {
    name: "Live Launch",
    configName: "liveLaunch",
    infoMsg:
      "Please click this check box, if you want Examd to conduct Live-launch. Live launch proctoring is an identity verification at the beginning of the exam or quiz. Here a human from our side will let the student start the quiz after verifying his/her identity.",
    settings: {
      recordWebcam: true,
      recordScreen: true,
      recordAudio: false,
      chat: false,
      studentPicture: false,
      studentIdDl: false,
      roomScan: true,
      otp: false,
      calculatorAllowed: false,
      scratchPadAllowed: false,
      liveHelp: false,
      whitelistPages: false,
      disableCopyPaste: true,
      disablePrinting: true,
      multiplePerson: true,
      cellPhone: true,
      noPersonInRoom: true,
      speaking: true,
      postExamReview: false,
      examdLiveLaunch: true,
      instructorProctored: false,
      examdProctored: false,
      lockdownBrowser: false,
    },
  },
  {
    name: "Live Proctoring",
    configName: "liveProctoring",
    infoMsg:
      "Please click this check box, if you want Examd to conduct full live proctoring. Live Proctoring is an identity verification and automated digital remote proctoring solution, helping Institutions of higher education ensure the integrity of their high-stakes online assessments. Here a human either from Institution or from our side will monitor the full exam.",
    settings: {
      recordWebcam: true,
      recordScreen: true,
      recordAudio: false,
      chat: false,
      studentPicture: false,
      studentIdDl: false,
      roomScan: false,
      otp: false,
      calculatorAllowed: false,
      scratchPadAllowed: false,
      liveHelp: false,
      whitelistPages: false,
      disableCopyPaste: true,
      disablePrinting: true,
      multiplePerson: true,
      cellPhone: true,
      noPersonInRoom: true,
      speaking: true,
      postExamReview: false,
      examdLiveLaunch: false,
      instructorProctored: false,
      examdProctored: true,
      lockdownBrowser: false,
    },
  },
  {
    name: "Lockdown Browser",
    configName: "lockdownBrowser",
    infoMsg:
      "Lockdown browser is an advanced technology that locks down test-takers' testing environment and restricts on-screen cheating during an online exam. It does not do video recording like the other options.",
    settings: {
      recordWebcam: false,
      recordScreen: false,
      recordAudio: false,
      chat: false,
      studentPicture: true,
      studentIdDl: true,
      roomScan: false,
      otp: false,
      calculatorAllowed: false,
      scratchPadAllowed: false,
      liveHelp: false,
      whitelistPages: false,
      disableCopyPaste: true,
      disablePrinting: true,
      multiplePerson: false,
      cellPhone: false,
      noPersonInRoom: false,
      speaking: false,
      postExamReview: false,
      examdLiveLaunch: false,
      instructorProctored: false,
      examdProctored: false,
      lockdownBrowser: true,
    },
  },
];

export const disabledConfigOptions: QuizConfigurationWithOnlyProcOpt = {
  calculatorAllowed: false,
  cellPhone: false,
  chat: false,
  disableCopyPaste: false,
  disablePrinting: false,
  examdLiveLaunch: false,
  examdProctored: false,
  instructorProctored: false,
  liveHelp: false,
  lockdownBrowser: false,
  multiplePerson: false,
  noPersonInRoom: false,
  otp: false,
  postExamReview: false,
  recordAudio: false,
  recordScreen: false,
  recordWebcam: false,
  roomScan: false,
  scratchPadAllowed: false,
  speaking: false,
  studentIdDl: false,
  studentPicture: false,
  whitelistPages: false
}

export const infoMsgs: { [key: string]: string } = {
  editCustomizationInfo: "When selecting any quiz you will see the default configuration for the quiz. If you want to change any configuration, please click this link.",
  repairModuleInfo: "When you configure the quiz for the first time, we run few automation to create the module, assignment, placement etc., if you by mistake delete any of the object created by automation please click this link, so that the proctoring module can be restored.",
  deleteCustomization: "Click this link if you want to Delete the proctoring option for the selected Quiz. All objects or records created for proctoring purpose will be deleted, and you can start over.",
  createSampleQuiz: "Click this if you want to create a sample quiz for the students. Students can take this 2 minute quiz to experience our proctoring process from start to finish."

}

export const generalInstructions: GeneralInstructions[] = [
  {
    name: "Config a new Quiz (Default)",
    infoMsg: ["Please select a quiz", "Select a checkbox, if you need any assistance from Examd.", "Click the Submit button at the bottom."]
  },
  {
    name: "Config a new Quiz (Customized)",
    infoMsg: ["Please select a quiz", "Please select the link Custmization and make changes.", "Click the Submit button at the bottom."]
  },
  {
    name: "Previously configured Quiz (Customized)",
    infoMsg: ["Please select a quiz", "Please select the link Custmization and make changes.", "Click the Submit button at the bottom."]
  },
]
